openapi: 3.0.0
info:
  title: CinemaHub API
  description: API para la gestión de reservas de cine, incluyendo películas, salas y reservas de asientos.
  version: 1.0.0

servers:
  - url: 'http://localhost:3000'
    description: Servidor local de desarrollo

paths:
  /movies:
    get:
      summary: Obtiene todas las películas
      responses:
        '200':
          description: Lista de películas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                      example: 'Inception'
                    genre:
                      type: string
                      example: 'Sci-Fi'
                    duration:
                      type: integer
                      example: 148
                    rating:
                      type: string
                      example: 'PG-13'
    post:
      summary: Crea una nueva película
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: 'Inception'
                genre:
                  type: string
                  example: 'Sci-Fi'
                duration:
                  type: integer
                  example: 148
                rating:
                  type: string
                  example: 'PG-13'
      responses:
        '201':
          description: Película creada con éxito

  /rooms:
    get:
      summary: Obtiene todas las salas
      responses:
        '200':
          description: Lista de salas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
    
