name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Ejecuta el pipeline cuando haya cambios en la rama 'main'
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod 
    steps:
      # Paso 1: Configurar Node.js
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Asegúrate de usar la versión adecuada

      - name: Install dependencies
        run: npm install

      # Paso 2: Compilar TypeScript
      - name: Build the project
        run: npm run build  # Este comando generará la carpeta dist con los archivos compilados

      # Paso 3: Empaquetar la Lambda
      - name: Package Lambda function
        run: |
          npm run deploy  # Empaqueta los archivos de la función Lambda en un archivo zip

      # Paso 4: Configurar AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Usa tus credenciales AWS en los secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Asegúrate de usar la región correcta

      # Paso 5: Desplegar en Lambda
      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code --function-name cinemahub-mngr --zip-file fileb://cinemahub-mngr.zip
